### ISSUE TITLE
Add retry mechanism for publish failures

### ISSUE THREAD

**Issue by edoardocostantinidev** [primait/amqpx#113]
Hello,
it would be nice to have a retry mechanism for the publish operation of a producer. 
The retry mechanism will be implemented with exponential backoff and a maximum number of retries per message.

Feature Configuration could be as follows:
```
{
  max_retries: int, #0 if not present/default
  retry_policy: [
    :on_publish_rejected,
    :on_confirm_timeout,
    :on_publish_error,
  ],
  backoff: [
    base_in_ms: 10,
    max_in_ms: 10_000
  ],
}
```
If you like this proposal we, as in @primait/scrooge, can tackle this issue in our friday coding activities. 

cc @michelangelomo @squaini @larrywax

**Comment by larrywax** [comment]
That would be great, thanks! 💜
