### ISSUE TITLE
Failed version check

### ISSUE THREAD

**Issue by parry84** [primait/amqpx#45]
While updating from 5.3.1 to 5.3.2 I'm not able to compile anymore. I get this error instead.

`Unchecked dependencies for environment dev:
* amqpx (Hex package)
  the dependency does not match the requirement "5.3.2", got "0.0.0-dev"
** (Mix) Can't continue due to errors on dependencies
`

I had a look at the mix.exs and noticed that we are reading the version number from DRONE_TAG env var rather than a well defined version string as in 5.3.1.

**Comment by michelangelomo** [comment]
Hi @parry84,
I tried to reproduce the issue with no success. Can you provide us more details?

**Comment by michelangelomo** [comment]
Issue fixed in [5.3.3](https://github.com/primait/amqpx/releases/tag/5.3.3)

**Comment by parry84** [comment]
Sorry, I didn't noticed your question. Thanks for the fix!
