### ISSUE TITLE
Consumer should not retry messages by default

### ISSUE THREAD

**Issue by fabriziosestito** [primait/amqpx#56]
README describes the backoff configuration as a "connection retry" parameter.

In the consumer genserver, the backoff parameter is also used to retry messages that raised an error directly or that did not match ```{:ok, _} ```
see: 
https://github.com/primait/amqpx/blob/a1327978ba000eeba9d9badb354833ebe23f2a36/lib/amqp/gen/consumer.ex#L201

**Expected behavior:**

The consumer should not retry messages by default and it should not use the same parameter for message/connection retries.

I can push a PR to fix this, thoughts?

**Comment by cando** [comment]
closed by #112 imho @michelangelomo
